export const HEADER_HEIGHT = 56
export const HEADER_BORDER_BOTTOM_COLOR = 'rgb(207, 217, 222)'
export const DIVIDER_COLOR = 'rgb(239, 243, 244)'
export const LOGO_URL = 'https://res.cloudinary.com/tuanrumah/image/upload/v1627058439/rental_app/twitter-logo.jpg'
export const PASSWORD_MAX_LENGTH = 30
export const USER_FULLNAME_MAX_LENGTH = 50
export const AD_ACCOUNT_NAME_MAX_LENGTH = 50
export const ADDRESS_MAX_LENGTH = 300
export const MOBILE_NUMBER_MAX_LENGTH = 15
export const WHATSAPP_VERIFICATION_CODE_MAX_LENGTH = 6
export const PRODUCT_TITLE_MAX_LENGTH = 100
export const PRODUCT_DESC_MAX_LENGTH = 4000
export const PRODUCT_SPEC_VALUE_MAX_LENGTH = 50
export const PRODUCT_NUMERIC_SPEC_VALUE_MAX_LENGTH = 14
export const PRODUCT_PRICE_MAX_LENGTH = 14
export const MAX_IMAGE_UPLOAD = 7